-- ==========================================
-- 0. 기초 인프라 및 환경 설정
-- ==========================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 가시성 설정 ENUM (이미 존재 시 무시)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'adminax_visibility_type') THEN
        CREATE TYPE adminax_visibility_type AS ENUM ('PUBLIC', 'PRIVATE', 'SHARED');
    END IF;
END $$;

-- 수정 시간 자동 업데이트 함수
CREATE OR REPLACE FUNCTION adminax_set_modified_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.modified_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- 1. 앱 설정 및 문서 로그
-- ==========================================
CREATE TABLE IF NOT EXISTS dev_config (
    id SERIAL PRIMARY KEY,
    config_key VARCHAR(255) NOT NULL UNIQUE,
    config_value JSONB NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO dev_config (config_key, config_value, description)
VALUES (
    'gemini_receipt_config', 
    '{
        "api_key": "PLACEHOLDER_KEY",
        "model_name": "gemini-1.5-flash",
        "base_url": "https://generativelanguage.googleapis.com",
        "api_version": "v1beta",
        "parameters": {
            "temperature": 0.1,
            "max_output_tokens": 4096,
            "top_p": 0.95,
            "response_mime_type": "application/json"
        },
        "system_instruction": "당신은 영수증 분석 전문가입니다. 이미지에서 상호명, 사업자번호, 일시, 합계금액, 품목 리스트를 추출하여 지정된 JSON 형식으로 응답하세요. 모든 텍스트는 원문 언어를 유지하세요."
    }'::jsonb,
    'AdminAX 영수증 분석용 Gemini 1.5 Flash API 설정'
)
ON CONFLICT (config_key) DO UPDATE SET 
    config_value = EXCLUDED.config_value,
    description = EXCLUDED.description;

CREATE TABLE IF NOT EXISTS document_logs (
    id SERIAL PRIMARY KEY,
    doc_id VARCHAR(100) NOT NULL,
    status VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ==========================================
-- 2. 유저 및 인증 시스템 (1:N)
-- ==========================================

-- 유저 메인 (Identity)
CREATE TABLE IF NOT EXISTS adminax_users (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 표준 ID 생성 방식
    user_uuid     UUID DEFAULT gen_random_uuid() NOT NULL,
    email         TEXT NOT NULL UNIQUE,
    full_name     TEXT NOT NULL,
    status        TEXT DEFAULT 'ACTIVE',
    is_admin      BOOLEAN DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at    TIMESTAMPTZ NULL,
    CONSTRAINT adminax_user_status_chk CHECK (status IN ('ACTIVE', 'SLEEP', 'WITHDRAWN', 'GUEST'))
);

-- 계정 인증 (Authentication Accounts)
CREATE TABLE IF NOT EXISTS adminax_user_accounts (
    account_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES adminax_users(user_id) ON DELETE CASCADE,
    provider         TEXT NOT NULL, -- LOCAL, KAKAO, NAVER, GOOGLE
    provider_user_id TEXT NOT NULL, 
    password_hash    TEXT NULL,
    last_login_at    TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ux_adminax_provider_id UNIQUE (provider, provider_user_id)
);

-- ==========================================
-- 3. 그룹 관리 시스템
-- ==========================================

CREATE TABLE IF NOT EXISTS adminax_groups (
    group_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name  TEXT NOT NULL,
    description TEXT,
    owner_id    BIGINT NOT NULL REFERENCES adminax_users(user_id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ NULL
);

CREATE TABLE IF NOT EXISTS adminax_group_members (
    group_id   BIGINT REFERENCES adminax_groups(group_id) ON DELETE CASCADE,
    user_id    BIGINT REFERENCES adminax_users(user_id) ON DELETE CASCADE,
    joined_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (group_id, user_id)
);

-- ==========================================
-- 4. 문서 관리 시스템 (폴더 & 문서)
-- ==========================================

CREATE TABLE IF NOT EXISTS adminax_folder_mng (
    folder_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_name        TEXT NOT NULL,
    parent_id          BIGINT NULL REFERENCES adminax_folder_mng(folder_id),
    owner_id           BIGINT NOT NULL REFERENCES adminax_users(user_id),
    inherit_visibility BOOLEAN NOT NULL DEFAULT TRUE,
    visibility         adminax_visibility_type NULL,
    target_group_id    BIGINT NULL REFERENCES adminax_groups(group_id),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at         TIMESTAMPTZ NULL,

    CONSTRAINT adminax_folder_inherit_logic_chk 
        CHECK (
            (inherit_visibility = TRUE AND visibility IS NULL) OR 
            (inherit_visibility = FALSE AND visibility IS NOT NULL)
        )
);

CREATE TABLE IF NOT EXISTS adminax_documents (
    doc_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_uuid        VARCHAR(36) NOT NULL, -- Java 발급용 (String UUID)
    folder_id       BIGINT NOT NULL REFERENCES adminax_folder_mng(folder_id),
    doc_name        TEXT NOT NULL,
    doc_path        TEXT NOT NULL,
    owner_id        BIGINT NOT NULL REFERENCES adminax_users(user_id),
    content         TEXT,
    summary         TEXT,
    keywords        TEXT[],
    canonical_json  JSONB,
    metadata        JSONB,
    search_vector   TSVECTOR,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ NULL
);

-- ==========================================
-- 5. AI 채팅 시스템
-- ==========================================

CREATE TABLE IF NOT EXISTS adminax_chat_room (
    room_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_uuid       UUID DEFAULT gen_random_uuid() NOT NULL,
    owner_id        BIGINT NOT NULL REFERENCES adminax_users(user_id),
    title           TEXT NOT NULL DEFAULT '새로운 대화',
    visibility      adminax_visibility_type NOT NULL DEFAULT 'PRIVATE',
    target_group_id BIGINT NULL REFERENCES adminax_groups(group_id),
    parent_room_id  BIGINT NULL REFERENCES adminax_chat_room(room_id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ NULL
);

CREATE TABLE IF NOT EXISTS adminax_chat_message (
    message_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id         BIGINT NOT NULL REFERENCES adminax_chat_room(room_id) ON DELETE CASCADE,
    role            TEXT NOT NULL,
    content         TEXT NOT NULL,
    referenced_docs JSONB NULL,
    tokens_used     INTEGER DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==========================================
-- 6. 인덱스 및 자동화 트리거
-- ==========================================

-- UUID 유니크 인덱스
CREATE UNIQUE INDEX IF NOT EXISTS ux_adminax_user_uuid ON adminax_users(user_uuid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_adminax_doc_uuid ON adminax_documents(doc_uuid);
CREATE UNIQUE INDEX IF NOT EXISTS ux_adminax_chat_uuid ON adminax_chat_room(room_uuid);

-- 검색 인덱스 (GIN)
CREATE INDEX IF NOT EXISTS idx_adminax_doc_fts ON adminax_documents USING GIN (search_vector);
CREATE INDEX IF NOT EXISTS idx_adminax_doc_keywords ON adminax_documents USING GIN (keywords);

-- 수정 시각 자동 업데이트 트리거 등록
DO $$ 
DECLARE 
    t text;
BEGIN
    FOR t IN SELECT table_name FROM information_schema.tables 
             WHERE table_name IN ('adminax_users', 'adminax_folder_mng', 'adminax_documents', 'adminax_chat_room', 'adminax_groups')
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_modtime ON %I', t, t);
        EXECUTE format('CREATE TRIGGER trg_%I_modtime BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION adminax_set_modified_at()', t, t);
    END LOOP;
END $$;

-- 검색 벡터 자동 갱신 트리거
CREATE OR REPLACE FUNCTION adminax_update_doc_search_vector()
RETURNS TRIGGER AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('simple', coalesce(NEW.doc_name, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.summary, '')), 'B') ||
    setweight(to_tsvector('simple', array_to_string(NEW.keywords, ' ')), 'B') ||
    setweight(to_tsvector('simple', coalesce(NEW.content, '')), 'C');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_adminax_doc_search_update ON adminax_documents;
CREATE TRIGGER trg_adminax_doc_search_update
BEFORE INSERT OR UPDATE OF doc_name, summary, keywords, content ON adminax_documents
FOR EACH ROW EXECUTE FUNCTION adminax_update_doc_search_vector();